Repository q191201771/lal, pull requests merged in 2022-11, with the labels that each got.

#241 [fix]gop增加单个gop包数量的限制
  conf/lalserver.conf.json
  conf/lalserver.conf.json.tmpl
  pkg/logic/config.go
  pkg/logic/group__.go
  pkg/remux/gop_cache.go
  pkg/remux/gop_cache_mpegts.go
  pkg/remux/gop_cache_test.go
Labels: *In process, #Opt

#244 Add example flv file of CustomPubSession
  app/demo/customize_lalserver/customize_lalserver.go
  pkg/logic/customize_pubsession.go
  pkg/logic/logic.go
Labels: *In process

#245 [Feat] - hls sub session
  conf/lalserver.conf.json
  pkg/base/error.go
  pkg/base/t_session.go
  pkg/base/t_unique.go
  pkg/hls/server_handler.go
  pkg/hls/server_sub_session.go
  pkg/logic/config.go
  pkg/logic/group__.go
  pkg/logic/group__out_sub.go
  pkg/logic/server_manager__.go
Labels: *In process

#247 add file close in ReadAllTagsFromFlvFile
  pkg/httpflv/util.go
Labels: *In process

#246 ci: add arm64 support
  .github/workflows/docker.yml
  build_for_linux.sh
Labels: *PR accepted, #Opt
