Repository q191201771/lal, pull requests merged in 2023-10, with the labels that each got.

#318 perf: optimize CPU consumption
  pkg/rtsp/client_command_session.go
Labels: #Performance

#322 [fix] 修复获取 hls 流名称
  pkg/hls/server_sub_session.go
Labels: #Bug, *In process

#324 chore: use bytes.Equal instead
  pkg/rtmp/handshake.go
Labels: #Performance, *In process
