Repository q191201771/lal, pull requests merged in 2023-04, with the labels that each got.

#272 rtsp客户端在SETUP阶段收到461时切换transport
  pkg/rtsp/client_command_session.go
Labels: *In process, #Opt

#273 开启http_API跨域
  pkg/logic/http_api.go
Labels: *PR accepted, #Opt

#275 解决CustomizePubSessionContext使用dumpFile空指针问题
  pkg/logic/customize_pubsession.go
Labels: #Bug, *In process

#276 rtmp推流支持enhanced RTMP
  pkg/base/t_rtmp.go
  pkg/hevc/hevc.go
  pkg/logic/group__core_streaming.go
  pkg/remux/rtmp2mpegts.go
  pkg/remux/rtmp2rtsp.go
Labels: #Feature, *In process
